version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: team-meta-demo
    volumes:
      - .:/var/www/html
    env_file: .env.docker
    depends_on:
      - mysql

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: vite-builder
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_meta
    ports:
      - "3306:3306"

volumes:
  mysql-data: